resolver: lts-6.35

extra-deps:
  - selda-0.1.11.0
  - selda-sqlite-0.1.6.0
  - shellmate-0.3.4.2
  - shellmate-extras-0.3.4.1
  - data-default-0.7.1.1
  - data-default-class-0.1.2.0
  - file-embed-0.0.10
  - http-conduit-2.2.3.2
  - http-client-0.5.7.0
  - http-client-tls-0.3.5.1
  - cereal-0.4.1.1
  - haste-app-0.1.0.0
  - haste-lib-0.6.0.0
  - haste-prim-0.6.0.0
