resolver: lts-6.35

packages:
  - location: .

  - location:
      git: https://github.com/valderman/haste-compiler.git
      commit: b9efe0f4fcdc4aa2a5f29b15dbf0725f3cacd237
    subdirs:
      - libraries/haste-lib
      - libraries/haste-prim
    extra-dep: true

  - location:
      git: https://github.com/valderman/haste-app.git
      commit: d8650663c4e02577ef0a658f224b3fe8f19bfc9e
    extra-dep: true


extra-deps:
  - selda-0.1.11.0
  - selda-sqlite-0.1.6.0
  - shellmate-0.3.4.2
  - shellmate-extras-0.3.4.1
  - data-default-0.7.1.1
  - data-default-class-0.1.2.0
  - file-embed-0.0.10
  - http-conduit-2.2.3.2
  - http-client-0.5.7.0
  - http-client-tls-0.3.5.1
  - cereal-0.4.1.1